In [51]:
import numpy as np

def A_h(func, nodes):
    temp = pad_along_axis(func,nodes,axis = 2)
    print(temp)
    for i in range(nodes):
        print(i)
        if i == 0:
            print("hello")
            temp[:,:,i] = func[:,:,i] / 2
        
        elif i > 0 and i < nodes-1:
            print("Goodbye")
            temp[:,:,i] = (func[:,:,i] + func[:,:,i-1]) / 2
        
        elif i == nodes-1:
            print("yes?")
            temp[:,:,i] = func[:,:,i-1]/2 
            
    return(temp)
    
def pad_along_axis(array: np.ndarray, target_length: int, axis: int = 0):
    pad_size = target_length - array.shape[axis]
    if pad_size <= 0:
        return array
    npad = [(0, 0)] * array.ndim
    npad[axis] = (0, pad_size)
    return np.pad(array, pad_width=npad, mode='constant', constant_values=0)

result = np.zeros((3, 3, 5))
   
result[:,:,0] = np.array(([[10, 11, 12], [13, 14, 15], [16, 17, 18]]))
result[:,:,1] = np.array(([[100, 110, 120], [130, 140, 150], [160, 170, 180]]))
result[:,:,2] = np.array(([[1000, 1100, 1200], [1300, 1400, 1500], [1600, 1700, 1800]]))
result[:,:,3] = np.array(([[10000, 11000, 12000], [13000, 14000, 15000], [16000, 17000, 18000]]))
result[:,:,4] = np.array(([[100000, 1100000, 1200000], [1300000, 1400000, 1500000], [1600000, 1700000, 1800000]]))
    

print(result[:,:,3])

abba = A_h(result, 6)
print(abba[:,:,5])


[[10000. 11000. 12000.]
 [13000. 14000. 15000.]
 [16000. 17000. 18000.]]
[[[1.0e+01 1.0e+02 1.0e+03 1.0e+04 1.0e+05 0.0e+00]
  [1.1e+01 1.1e+02 1.1e+03 1.1e+04 1.1e+06 0.0e+00]
  [1.2e+01 1.2e+02 1.2e+03 1.2e+04 1.2e+06 0.0e+00]]

 [[1.3e+01 1.3e+02 1.3e+03 1.3e+04 1.3e+06 0.0e+00]
  [1.4e+01 1.4e+02 1.4e+03 1.4e+04 1.4e+06 0.0e+00]
  [1.5e+01 1.5e+02 1.5e+03 1.5e+04 1.5e+06 0.0e+00]]

 [[1.6e+01 1.6e+02 1.6e+03 1.6e+04 1.6e+06 0.0e+00]
  [1.7e+01 1.7e+02 1.7e+03 1.7e+04 1.7e+06 0.0e+00]
  [1.8e+01 1.8e+02 1.8e+03 1.8e+04 1.8e+06 0.0e+00]]]
0
hello
1
Goodbye
2
Goodbye
3
Goodbye
4
Goodbye
5
yes?
[[ 50000. 550000. 600000.]
 [650000. 700000. 750000.]
 [800000. 850000. 900000.]]


In [60]:
print(abba)

print(abba[:,:,6])

[[[5.000e+00 5.500e+01 5.500e+02 5.500e+03 5.500e+04 5.000e+04]
  [5.500e+00 6.050e+01 6.050e+02 6.050e+03 5.555e+05 5.500e+05]
  [6.000e+00 6.600e+01 6.600e+02 6.600e+03 6.060e+05 6.000e+05]]

 [[6.500e+00 7.150e+01 7.150e+02 7.150e+03 6.565e+05 6.500e+05]
  [7.000e+00 7.700e+01 7.700e+02 7.700e+03 7.070e+05 7.000e+05]
  [7.500e+00 8.250e+01 8.250e+02 8.250e+03 7.575e+05 7.500e+05]]

 [[8.000e+00 8.800e+01 8.800e+02 8.800e+03 8.080e+05 8.000e+05]
  [8.500e+00 9.350e+01 9.350e+02 9.350e+03 8.585e+05 8.500e+05]
  [9.000e+00 9.900e+01 9.900e+02 9.900e+03 9.090e+05 9.000e+05]]]


IndexError: index 6 is out of bounds for axis 2 with size 6

###### for x in range(6):
  print(x) 
